---
title: "Dashboard for HW 4"
output: 
  flexdashboard::flex_dashboard
---

```{r setup, message = FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(patchwork)
library(httr)
library(jsonlite)
library(janitor)
```


# Which type of cuisine has the highest count of "Critical"?

```{r message=FALSE, echo=FALSE}
rest_inspec %>% 
  group_by(cuisine_description) %>%
  summarize(num_critical = sum(critical_flag=="Critical")) %>%
  plot_ly(x = ~cuisine_description, y = ~num_critical, type = "bar") %>% 
  layout(xaxis = list(title = "Type of Cuisine"), yaxis = list(title ="Count of critical incidence"))
```

# NYC restaurants score by different boros

```{r message=FALSE, echo=FALSE}
rest_inspec %>%
  group_by(boro) %>%
  drop_na(score)%>%
  plot_ly(x = ~boro, y = ~score, type = "box", color = ~boro) %>%
  layout(xaxis = list(title = "NYC boros"), yaxis = list(title = "Score"))
```


```{r message=FALSE, echo=FALSE}
rest_inspec %>%
  group_by(critical_flag) %>%
  drop_na(score)%>%
  plot_ly( y = ~score, type = "scatter", color = ~critical_flag) %>%
  layout(xaxis = list(title = "NYC boros"), yaxis = list(title = "Score"))
```

